spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Zhwq1234
    #url: jdbc:mysql://116.62.172.49:3306/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://101.37.149.241:3307/sell?characterEncoding=utf-8&useSSL=false
    hikari:
       minimum-idle:5
       maximum-pool-size:15
       auto-commit:true
       idle-timeout:30000
       pool-name:DatebookHikariCP
       max-lifetime:1800000
       connection-timeout:30000
       connection-test-query:SELECT 1
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password: test@2018
    

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  # 公众账号, 授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret:

  # 开放平台,  卖家扫码登录用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9xxxxxx

  # 支付/商户号
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  # 发起支付不需要证书, 退款需要
  keyPath:
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://lsx888.natapp1.cc
  wechatOpenAuthorize: http://lsx888.natapp1.cc
  #sell: http://lsx888.natapp1.cc
  sell: http://101.37.149.241:8084
  #sell: http://localhost:8080

logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

# 又拍云服务 见 https://console.upyun.com/services/file/
upyun:
  bucketName: image-liren
  userName: panel
  password: VgDsHsffkYEBRXMQypofMDX7Rw6ufKLt
  imageHost: http://image-liren.test.upcdn.net/
server:
  port: 8084
  servlet:
    context-path: /sell
  session: 
    timeout: 72000
    